### ISSUE TITLE
Адаптация под разные усилители 

### ISSUE THREAD

**Issue by shax-xxx** [GyverLibs/VolAnalyzer#1]
Здравствуйте.
Я, насколько понимаю, библиотека адаптирована под модуль max9814, который умеет усиливать выходной сигнал от 40 до 60dB. 
Я пытаюсь понять как адаптировать её под модули с фиксированным коэффициентом, например под max9813 или max9812 (20dB).
Из описания использования мало понятно, где домножить тот самый raw value, чтобы функции библиотеки не заметили подмену :)
Всё это для сборки гайверлампы со звуком, но тут кажется этот вопрос более уместен.

здесь есть пример кода для max9812:
[max9812](https://sites.google.com/site/myscratchbooks/home/projects/project-19-using-max9812-mensaure-decibels-db-db-spl)

Может вы подскажите как из 20dB получить 40 в рамках вашей библиотеки

**Comment by shax-xxx** [comment]
кажется нашёл.
в функции tick() можно просто домножить получаемое значение read.

**Comment by GyverLibs** [comment]
Библиотека работает с любым аналоговым звуковым сигналом любой громкости, о конкретных микросхемах речи не идёт

**Comment by shax-xxx** [comment]
Поторопился я с вопросом в порыве увеличить чувствительность. 
Прошу прощения.

**Comment by GyverLibs** [comment]
Библиотека адаптируется пол любой сигнал, возможно нужно поиграться с настройками коэффициентов

**Comment by shax-xxx** [comment]
Да, спасибо. 
Пока смотрю на эти:
    int _trsh = 40;
    int _volMin = 0, _volMax = 100;

**Comment by GyverLibs** [comment]
Это не то. Всё настраивается из скетча, в документации всё расписано

**Comment by shax-xxx** [comment]
Вы про это?

```
void setTrsh(int trsh);         // установить порог громкости в единицах raw АЦП (умолч 40)

// громкость
void setVolK(byte k);           // установить коэффициент фильтрации громкости 0-31 (умолч 25)
void setVolMin(int scale);      // установить минимальную величину громкости (умолч 0)
void setVolMax(int scale);      // установить максимальную величину громкости (умолч 100)

```

**Comment by GyverLibs** [comment]
ага
